title: Arun Ramanathan # your name (or website title) here
#logo: "35426 ARUN.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Included repositories containing project and solutions of algorithic problems. 
  
theme: jekyll-theme-minimal
#google_analytics: UA-000000-0 # your Google Analytics tracking ID here
